package br.com.conductor.pier.api.v2.model;

import java.math.BigDecimal;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


/**
 * Parcel of agreement
 **/
@ApiModel(description = "Parcel of agreement")
public class ParcelaAcordoResponse  {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("idAcordo")
  private Long idAcordo = null;
  @SerializedName("numeroParcela")
  private Integer numeroParcela = null;
  @SerializedName("valorParcela")
  private BigDecimal valorParcela = null;
  @SerializedName("vencimentoParcela")
  private String vencimentoParcela = null;
  @SerializedName("saldoParcela")
  private BigDecimal saldoParcela = null;
  @SerializedName("nossoNumero")
  private String nossoNumero = null;
  @SerializedName("idBoletoParcela")
  private Long idBoletoParcela = null;

  
  /**
   * Identification code of the agreement portion
   **/
  @ApiModelProperty(value = "Identification code of the agreement portion")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  
  /**
   * Identification Code of the Agreement (ID)
   **/
  @ApiModelProperty(value = "Identification Code of the Agreement (ID)")
  public Long getIdAcordo() {
    return idAcordo;
  }
  public void setIdAcordo(Long idAcordo) {
    this.idAcordo = idAcordo;
  }

  
  /**
   * Plot Number
   **/
  @ApiModelProperty(value = "Plot Number")
  public Integer getNumeroParcela() {
    return numeroParcela;
  }
  public void setNumeroParcela(Integer numeroParcela) {
    this.numeroParcela = numeroParcela;
  }

  
  /**
   * Plot amount
   **/
  @ApiModelProperty(value = "Plot amount")
  public BigDecimal getValorParcela() {
    return valorParcela;
  }
  public void setValorParcela(BigDecimal valorParcela) {
    this.valorParcela = valorParcela;
  }

  
  /**
   * Maturity Date
   **/
  @ApiModelProperty(value = "Maturity Date")
  public String getVencimentoParcela() {
    return vencimentoParcela;
  }
  public void setVencimentoParcela(String vencimentoParcela) {
    this.vencimentoParcela = vencimentoParcela;
  }

  
  /**
   * Portion balance
   **/
  @ApiModelProperty(value = "Portion balance")
  public BigDecimal getSaldoParcela() {
    return saldoParcela;
  }
  public void setSaldoParcela(BigDecimal saldoParcela) {
    this.saldoParcela = saldoParcela;
  }

  
  /**
   * Our number generated by parcel
   **/
  @ApiModelProperty(value = "Our number generated by parcel")
  public String getNossoNumero() {
    return nossoNumero;
  }
  public void setNossoNumero(String nossoNumero) {
    this.nossoNumero = nossoNumero;
  }

  
  /**
   * Ticket identification code
   **/
  @ApiModelProperty(value = "Ticket identification code")
  public Long getIdBoletoParcela() {
    return idBoletoParcela;
  }
  public void setIdBoletoParcela(Long idBoletoParcela) {
    this.idBoletoParcela = idBoletoParcela;
  }

  

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParcelaAcordoResponse {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  idAcordo: ").append(idAcordo).append("\n");
    sb.append("  numeroParcela: ").append(numeroParcela).append("\n");
    sb.append("  valorParcela: ").append(valorParcela).append("\n");
    sb.append("  vencimentoParcela: ").append(vencimentoParcela).append("\n");
    sb.append("  saldoParcela: ").append(saldoParcela).append("\n");
    sb.append("  nossoNumero: ").append(nossoNumero).append("\n");
    sb.append("  idBoletoParcela: ").append(idBoletoParcela).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
