package br.com.conductor.pier.api.v2.model;

import br.com.conductor.pier.api.v2.model.MapOfstringAndstring;
import java.util.*;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;


/**
 * Object Response of Authorization
 **/
@ApiModel(description = "Object Response of Authorization")
public class TransacaoOnUsResponse  {
  
  @SerializedName("nsuOrigem")
  private String nsuOrigem = null;
  @SerializedName("nsuAutorizacao")
  private String nsuAutorizacao = null;
  @SerializedName("planoDeParcelamento")
  private List<MapOfstringAndstring> planoDeParcelamento = null;
  @SerializedName("codigoAutorizacao")
  private String codigoAutorizacao = null;
  @SerializedName("numeroMascaradoCartao")
  private String numeroMascaradoCartao = null;
  @SerializedName("nomePortadorCartao")
  private String nomePortadorCartao = null;
  @SerializedName("terminalRequisitante")
  private String terminalRequisitante = null;

  
  /**
   * Unique Sequel Number that identifies the transaction in the system that originated it
   **/
  @ApiModelProperty(value = "Unique Sequel Number that identifies the transaction in the system that originated it")
  public String getNsuOrigem() {
    return nsuOrigem;
  }
  public void setNsuOrigem(String nsuOrigem) {
    this.nsuOrigem = nsuOrigem;
  }

  
  /**
   * Unique Sequel Number generated by the Authorizer to each Transaction
   **/
  @ApiModelProperty(value = "Unique Sequel Number generated by the Authorizer to each Transaction")
  public String getNsuAutorizacao() {
    return nsuAutorizacao;
  }
  public void setNsuAutorizacao(String nsuAutorizacao) {
    this.nsuAutorizacao = nsuAutorizacao;
  }

  
  /**
   * Description of the Installment Plan attributed to the Transaction
   **/
  @ApiModelProperty(value = "Description of the Installment Plan attributed to the Transaction")
  public List<MapOfstringAndstring> getPlanoDeParcelamento() {
    return planoDeParcelamento;
  }
  public void setPlanoDeParcelamento(List<MapOfstringAndstring> planoDeParcelamento) {
    this.planoDeParcelamento = planoDeParcelamento;
  }

  
  /**
   * Authorization Code generated by the Authorizer
   **/
  @ApiModelProperty(value = "Authorization Code generated by the Authorizer")
  public String getCodigoAutorizacao() {
    return codigoAutorizacao;
  }
  public void setCodigoAutorizacao(String codigoAutorizacao) {
    this.codigoAutorizacao = codigoAutorizacao;
  }

  
  /**
   * Card Number that originated the transaction in the masked format
   **/
  @ApiModelProperty(value = "Card Number that originated the transaction in the masked format")
  public String getNumeroMascaradoCartao() {
    return numeroMascaradoCartao;
  }
  public void setNumeroMascaradoCartao(String numeroMascaradoCartao) {
    this.numeroMascaradoCartao = numeroMascaradoCartao;
  }

  
  /**
   * Cardholder name that originated the transaction
   **/
  @ApiModelProperty(value = "Cardholder name that originated the transaction")
  public String getNomePortadorCartao() {
    return nomePortadorCartao;
  }
  public void setNomePortadorCartao(String nomePortadorCartao) {
    this.nomePortadorCartao = nomePortadorCartao;
  }

  
  /**
   * Show the indentification of the Requesting Terminal
   **/
  @ApiModelProperty(required = true, value = "Show the indentification of the Requesting Terminal")
  public String getTerminalRequisitante() {
    return terminalRequisitante;
  }
  public void setTerminalRequisitante(String terminalRequisitante) {
    this.terminalRequisitante = terminalRequisitante;
  }

  

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransacaoOnUsResponse {\n");
    
    sb.append("  nsuOrigem: ").append(nsuOrigem).append("\n");
    sb.append("  nsuAutorizacao: ").append(nsuAutorizacao).append("\n");
    sb.append("  planoDeParcelamento: ").append(planoDeParcelamento).append("\n");
    sb.append("  codigoAutorizacao: ").append(codigoAutorizacao).append("\n");
    sb.append("  numeroMascaradoCartao: ").append(numeroMascaradoCartao).append("\n");
    sb.append("  nomePortadorCartao: ").append(nomePortadorCartao).append("\n");
    sb.append("  terminalRequisitante: ").append(terminalRequisitante).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
